// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zl_WGp-dS_faXfSN8HdfAMTQTXj0xo4',
    appId: '1:281478719554:web:f30667e5ea0130863965db',
    messagingSenderId: '281478719554',
    projectId: 'smart-lady',
    authDomain: 'smart-lady.firebaseapp.com',
    storageBucket: 'smart-lady.appspot.com',
    measurementId: 'G-XFL6HZ7VCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUn9wVv9XCAAU9SGK2yAP4lmmxoscwNVw',
    appId: '1:281478719554:android:13aef7e28b1d8d443965db',
    messagingSenderId: '281478719554',
    projectId: 'smart-lady',
    storageBucket: 'smart-lady.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCYRGNbQ08P0RROWGzTifg3b2XyF8Wgo',
    appId: '1:281478719554:ios:77fcba2ae675f0193965db',
    messagingSenderId: '281478719554',
    projectId: 'smart-lady',
    storageBucket: 'smart-lady.appspot.com',
    iosClientId: '281478719554-nehng023g94n04cm4u7b8dea793tg663.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson1',
  );
}
